on:
  release:
    types: [created]

jobs:

  build-push-release:
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: firecow
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build and push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 . -t firecow/cloudflared:${{ github.event.release.tag_name }} --push
          docker buildx build --platform linux/amd64,linux/arm64 . -t firecow/cloudflared:latest --push
